init:
    - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: 0.11
    - nodejs_version: 0.12
    - nodejs_version: 1

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - git submodule update --init --recursive
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test
