init:
    - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: 0.11
    - nodejs_version: 0.12
    - nodejs_version: 1

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - git submodule update --init --recursive
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - node-gyp configure build
  - npm test
